"""add colemn created_at, updated_at

Revision ID: dfa67fc37fa4
Revises: a9552601e6be
Create Date: 2026-03-29 19:26:04.861186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa67fc37fa4'
down_revision: Union[str, Sequence[str], None] = 'a9552601e6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('wallets', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'created_at')
    # ### end Alembic commands ###
